apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - e2e-ec.yaml
patches:
  - path: hacbs-test.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      labelSelector: skip-hacbs-test != true
  - path: annotations.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
  - path: force-rebuild.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      labelSelector: skip-hacbs-test != true
#  - path: hacbs-java-builds.yaml
#    target:
#      group: tekton.dev
#      version: v1beta1
#      kind: Pipeline
#      labelSelector: skip-hacbs-test != true, pipelines.openshift.io/runtime == java
#  - path: hacbs-java-builds.yaml
#    target:
#      group: tekton.dev
#      version: v1beta1
#      kind: Pipeline
#      labelSelector: skip-hacbs-test != true, pipelines.openshift.io/runtime == generic
