apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../hacbs

patches:
  - path: infra-deploy.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      labelSelector: skip-hacbs-test != true
  - path: csi-secret.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      labelSelector: skip-hacbs-test != true
  - path: temp-disable-cache.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      labelSelector: skip-hacbs-test != true, pipelines.openshift.io/runtime == java
  - path: temp-disable-cache.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      labelSelector: skip-hacbs-test != true, pipelines.openshift.io/runtime == generic